from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate
from timesheet.sql_bd import scratch
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(763, 484)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(20, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setCurrentSectionIndex(0)
        self.dateEdit.setObjectName("dateEdit_data_months")
        self.dateEdit.setDate(QDate.currentDate())
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(240, 70, 461, 361))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 120, 121, 41))
        self.pushButton.clicked.connect(self.handler_button_click_date)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton_date")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def handler_button_click_date(self):
        selected_date = self.dateEdit.date().toString("MM.yyyy")
        self.dateEdit.parent().close()  # Закрываем окно
        self.new_form = QtWidgets.QWidget()  # Создаем новое окно
        self.open_timesheet_date(self.new_form)
        self.new_form.show()

    def open_timesheet_date(self, From_1):
        From_1.setObjectName("From_1")
        From_1.resize(1122, 893)
        self.label_0 = QtWidgets.QLabel(From_1)
        self.label_0.setGeometry(QtCore.QRect(20, 0, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_0.setFont(font)
        self.label_0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_0.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(From_1)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comboBox_1 = QtWidgets.QComboBox(From_1)
        self.comboBox_1.setGeometry(QtCore.QRect(20, 40, 201, 31))
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItems(scratch.update_work_team())
        self.comboBox_1.insertItem(0,"Все")
        self.comboBox_1.setCurrentIndex(0)
        self.comboBox_2 = QtWidgets.QComboBox(From_1)
        self.comboBox_2.setGeometry(QtCore.QRect(290, 40, 421, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItems(scratch.update_name_SNP())
        self.comboBox_2.insertItem(0,"Все")
        self.comboBox_2.setCurrentIndex(0)
        self.tableWidget = QtWidgets.QTableWidget(From_1)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 1101, 801))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.retranslateUi_1(From_1)
        QtCore.QMetaObject.connectSlotsByName(From_1)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Табель"))
        self.label.setText(_translate("Form", "Дата"))
        self.dateEdit.setDisplayFormat(_translate("Form", "MM.yyyy"))
        self.pushButton.setText(_translate("Form", "Табель"))

    def retranslateUi_1(self, Form_1):
        _translate = QtCore.QCoreApplication.translate
        Form_1.setWindowTitle(_translate("Form_1", "Табель по сотрудникам"))
        self.label_0.setText(_translate("Form_1", "Смена / график"))
        self.label_2.setText(_translate("Form_1", "Сотрудник"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.open_timesheet_date(Form)
    Form.show()
    sys.exit(app.exec_())

